Traceback (most recent call last):
  File "/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/biochemist-python/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
protein = mda.Universe("pdb/protein_H.pdb")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
    [0;31m[... skipping hidden 1 frame][0m

Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m protein [38;5;241m=[39m [43mmda[49m[38;5;241;43m.[39;49m[43mUniverse[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mpdb/protein_H.pdb[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:356[0m, in [0;36mUniverse.__init__[0;34m(self, topology, all_coordinates, format, topology_format, transformations, guess_bonds, vdwradii, fudge_factor, lower_bound, in_memory, in_memory_step, *coordinates, **kwargs)[0m
[1;32m    355[0m     [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;241m=[39m _check_file_like(topology)
[0;32m--> 356[0m     topology [38;5;241m=[39m [43m_topology_from_file_like[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m,[49m
[1;32m    357[0m [43m                                        [49m[43mtopology_format[49m[38;5;241;43m=[39;49m[43mtopology_format[49m[43m,[49m
[1;32m    358[0m [43m                                        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    360[0m [38;5;28;01mif[39;00m topology [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:118[0m, in [0;36m_topology_from_file_like[0;34m(topology_file, topology_format, **kwargs)[0m
[1;32m    115[0m [38;5;28;01mif[39;00m (err[38;5;241m.[39merrno [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m
[1;32m    116[0m     errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]):
[1;32m    117[0m     [38;5;66;03m# Runs if the error is propagated due to no permission / file not found[39;00m
[0;32m--> 118[0m     [38;5;28;01mraise[39;00m sys[38;5;241m.[39mexc_info()[[38;5;241m1[39m] [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    119[0m [38;5;28;01melse[39;00m:
[1;32m    120[0m     [38;5;66;03m# Runs when the parser fails[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:110[0m, in [0;36m_topology_from_file_like[0;34m(topology_file, topology_format, **kwargs)[0m
[1;32m    109[0m     [38;5;28;01mwith[39;00m parser(topology_file) [38;5;28;01mas[39;00m p:
[0;32m--> 110[0m         topology [38;5;241m=[39m [43mp[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    111[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    112[0m     [38;5;66;03m# There are 2 kinds of errors that might be raised here:[39;00m
[1;32m    113[0m     [38;5;66;03m# one because the file isn't present[39;00m
[1;32m    114[0m     [38;5;66;03m# or the permissions are bad, second when the parser fails[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:210[0m, in [0;36mPDBParser.parse[0;34m(self, **kwargs)[0m
[1;32m    204[0m [38;5;250m[39m[38;5;124;03m"""Parse atom information from PDB file[39;00m
[1;32m    205[0m 
[1;32m    206[0m [38;5;124;03mReturns[39;00m
[1;32m    207[0m [38;5;124;03m-------[39;00m
[1;32m    208[0m [38;5;124;03mMDAnalysis Topology object[39;00m
[1;32m    209[0m [38;5;124;03m"""[39;00m
[0;32m--> 210[0m top [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_parseatoms[49m[43m([49m[43m)[49m
[1;32m    212[0m [38;5;28;01mtry[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:247[0m, in [0;36mPDBParser._parseatoms[0;34m(self)[0m
[1;32m    246[0m last_wrapped_serial [38;5;241m=[39m [38;5;241m100000[39m  [38;5;66;03m# if serials wrap, start from here[39;00m
[0;32m--> 247[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43mopenany[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m)[49m[43m [49m[38;5;28;43;01mas[39;49;00m[43m [49m[43mf[49m[43m:[49m
[1;32m    248[0m [43m    [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mline[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[43mf[49m[43m:[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/contextlib.py:137[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    136[0m [38;5;28;01mtry[39;00m:
[0;32m--> 137[0m     [38;5;28;01mreturn[39;00m [38;5;28mnext[39m([38;5;28mself[39m[38;5;241m.[39mgen)
[1;32m    138[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:318[0m, in [0;36mopenany[0;34m(datasource, mode, reset)[0m
[1;32m    276[0m [38;5;250m[39m[38;5;124;03m"""Context manager for :func:`anyopen`.[39;00m
[1;32m    277[0m 
[1;32m    278[0m [38;5;124;03mOpen the `datasource` and close it when the context of the :keyword:`with`[39;00m
[0;32m   (...)[0m
[1;32m    316[0m [38;5;124;03m:func:`anyopen`[39;00m
[1;32m    317[0m [38;5;124;03m"""[39;00m
[0;32m--> 318[0m stream [38;5;241m=[39m [43manyopen[49m[43m([49m[43mdatasource[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m,[49m[43m [49m[43mreset[49m[38;5;241;43m=[39;49m[43mreset[49m[43m)[49m
[1;32m    319[0m [38;5;28;01mtry[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:398[0m, in [0;36manyopen[0;34m(datasource, mode, reset)[0m
[1;32m    397[0m openfunc [38;5;241m=[39m read_handlers[ext]
[0;32m--> 398[0m stream [38;5;241m=[39m [43m_get_stream[49m[43m([49m[43mdatasource[49m[43m,[49m[43m [49m[43mopenfunc[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[1;32m    399[0m [38;5;28;01mif[39;00m stream [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:440[0m, in [0;36m_get_stream[0;34m(filename, openfunction, mode)[0m
[1;32m    439[0m [38;5;28;01mif[39;00m errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]:
[0;32m--> 440[0m     [38;5;28;01mraise[39;00m sys[38;5;241m.[39mexc_info()[[38;5;241m1[39m] [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    441[0m [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:434[0m, in [0;36m_get_stream[0;34m(filename, openfunction, mode)[0m
[1;32m    433[0m [38;5;28;01mtry[39;00m:
[0;32m--> 434[0m     stream [38;5;241m=[39m [43mopenfunction[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[1;32m    435[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    436[0m     [38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this[39;00m
[1;32m    437[0m     [38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because[39;00m
[1;32m    438[0m     [38;5;66;03m# either the file isn't there or the permissions don't allow access.[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:502[0m, in [0;36mbz2_pickle_open[0;34m(name, mode)[0m
[1;32m    501[0m bz_mode [38;5;241m=[39m mode[38;5;241m.[39mreplace([38;5;124m"[39m[38;5;124mt[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m"[39m)
[0;32m--> 502[0m binary_file [38;5;241m=[39m [43mBZ2Picklable[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mbz_mode[49m[43m)[49m
[1;32m    503[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mt[39m[38;5;124m"[39m [38;5;129;01min[39;00m mode:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:283[0m, in [0;36mBZ2Picklable.__init__[0;34m(self, name, mode)[0m
[1;32m    282[0m [38;5;28mself[39m[38;5;241m.[39m_bz_mode [38;5;241m=[39m mode
[0;32m--> 283[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/bz2.py:81[0m, in [0;36mBZ2File.__init__[0;34m(self, filename, mode, compresslevel)[0m
[1;32m     80[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(filename, ([38;5;28mstr[39m, [38;5;28mbytes[39m, os[38;5;241m.[39mPathLike)):
[0;32m---> 81[0m     [38;5;28mself[39m[38;5;241m.[39m_fp [38;5;241m=[39m [43m_builtin_open[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m     82[0m     [38;5;28mself[39m[38;5;241m.[39m_closefp [38;5;241m=[39m [38;5;28;01mTrue[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'pdb/protein_H.pdb'

The above exception was the direct cause of the following exception:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
    [0;31m[... skipping hidden 1 frame][0m

Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m protein [38;5;241m=[39m [43mmda[49m[38;5;241;43m.[39;49m[43mUniverse[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mpdb/protein_H.pdb[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:356[0m, in [0;36mUniverse.__init__[0;34m(self, topology, all_coordinates, format, topology_format, transformations, guess_bonds, vdwradii, fudge_factor, lower_bound, in_memory, in_memory_step, *coordinates, **kwargs)[0m
[1;32m    355[0m     [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;241m=[39m _check_file_like(topology)
[0;32m--> 356[0m     topology [38;5;241m=[39m [43m_topology_from_file_like[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m,[49m
[1;32m    357[0m [43m                                        [49m[43mtopology_format[49m[38;5;241;43m=[39;49m[43mtopology_format[49m[43m,[49m
[1;32m    358[0m [43m                                        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    360[0m [38;5;28;01mif[39;00m topology [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:118[0m, in [0;36m_topology_from_file_like[0;34m(topology_file, topology_format, **kwargs)[0m
[1;32m    115[0m [38;5;28;01mif[39;00m (err[38;5;241m.[39merrno [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m
[1;32m    116[0m     errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]):
[1;32m    117[0m     [38;5;66;03m# Runs if the error is propagated due to no permission / file not found[39;00m
[0;32m--> 118[0m     [38;5;28;01mraise[39;00m sys[38;5;241m.[39mexc_info()[[38;5;241m1[39m] [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    119[0m [38;5;28;01melse[39;00m:
[1;32m    120[0m     [38;5;66;03m# Runs when the parser fails[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:110[0m, in [0;36m_topology_from_file_like[0;34m(topology_file, topology_format, **kwargs)[0m
[1;32m    109[0m     [38;5;28;01mwith[39;00m parser(topology_file) [38;5;28;01mas[39;00m p:
[0;32m--> 110[0m         topology [38;5;241m=[39m [43mp[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    111[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    112[0m     [38;5;66;03m# There are 2 kinds of errors that might be raised here:[39;00m
[1;32m    113[0m     [38;5;66;03m# one because the file isn't present[39;00m
[1;32m    114[0m     [38;5;66;03m# or the permissions are bad, second when the parser fails[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:210[0m, in [0;36mPDBParser.parse[0;34m(self, **kwargs)[0m
[1;32m    204[0m [38;5;250m[39m[38;5;124;03m"""Parse atom information from PDB file[39;00m
[1;32m    205[0m 
[1;32m    206[0m [38;5;124;03mReturns[39;00m
[1;32m    207[0m [38;5;124;03m-------[39;00m
[1;32m    208[0m [38;5;124;03mMDAnalysis Topology object[39;00m
[1;32m    209[0m [38;5;124;03m"""[39;00m
[0;32m--> 210[0m top [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_parseatoms[49m[43m([49m[43m)[49m
[1;32m    212[0m [38;5;28;01mtry[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:247[0m, in [0;36mPDBParser._parseatoms[0;34m(self)[0m
[1;32m    246[0m last_wrapped_serial [38;5;241m=[39m [38;5;241m100000[39m  [38;5;66;03m# if serials wrap, start from here[39;00m
[0;32m--> 247[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43mopenany[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m)[49m[43m [49m[38;5;28;43;01mas[39;49;00m[43m [49m[43mf[49m[43m:[49m
[1;32m    248[0m [43m    [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mline[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[43mf[49m[43m:[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/contextlib.py:137[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    136[0m [38;5;28;01mtry[39;00m:
[0;32m--> 137[0m     [38;5;28;01mreturn[39;00m [38;5;28mnext[39m([38;5;28mself[39m[38;5;241m.[39mgen)
[1;32m    138[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:318[0m, in [0;36mopenany[0;34m(datasource, mode, reset)[0m
[1;32m    276[0m [38;5;250m[39m[38;5;124;03m"""Context manager for :func:`anyopen`.[39;00m
[1;32m    277[0m 
[1;32m    278[0m [38;5;124;03mOpen the `datasource` and close it when the context of the :keyword:`with`[39;00m
[0;32m   (...)[0m
[1;32m    316[0m [38;5;124;03m:func:`anyopen`[39;00m
[1;32m    317[0m [38;5;124;03m"""[39;00m
[0;32m--> 318[0m stream [38;5;241m=[39m [43manyopen[49m[43m([49m[43mdatasource[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m,[49m[43m [49m[43mreset[49m[38;5;241;43m=[39;49m[43mreset[49m[43m)[49m
[1;32m    319[0m [38;5;28;01mtry[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:398[0m, in [0;36manyopen[0;34m(datasource, mode, reset)[0m
[1;32m    397[0m openfunc [38;5;241m=[39m read_handlers[ext]
[0;32m--> 398[0m stream [38;5;241m=[39m [43m_get_stream[49m[43m([49m[43mdatasource[49m[43m,[49m[43m [49m[43mopenfunc[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[1;32m    399[0m [38;5;28;01mif[39;00m stream [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:440[0m, in [0;36m_get_stream[0;34m(filename, openfunction, mode)[0m
[1;32m    439[0m [38;5;28;01mif[39;00m errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]:
[0;32m--> 440[0m     [38;5;28;01mraise[39;00m sys[38;5;241m.[39mexc_info()[[38;5;241m1[39m] [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    441[0m [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:434[0m, in [0;36m_get_stream[0;34m(filename, openfunction, mode)[0m
[1;32m    433[0m [38;5;28;01mtry[39;00m:
[0;32m--> 434[0m     stream [38;5;241m=[39m [43mopenfunction[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[1;32m    435[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    436[0m     [38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this[39;00m
[1;32m    437[0m     [38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because[39;00m
[1;32m    438[0m     [38;5;66;03m# either the file isn't there or the permissions don't allow access.[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:502[0m, in [0;36mbz2_pickle_open[0;34m(name, mode)[0m
[1;32m    501[0m bz_mode [38;5;241m=[39m mode[38;5;241m.[39mreplace([38;5;124m"[39m[38;5;124mt[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m"[39m)
[0;32m--> 502[0m binary_file [38;5;241m=[39m [43mBZ2Picklable[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mbz_mode[49m[43m)[49m
[1;32m    503[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mt[39m[38;5;124m"[39m [38;5;129;01min[39;00m mode:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:283[0m, in [0;36mBZ2Picklable.__init__[0;34m(self, name, mode)[0m
[1;32m    282[0m [38;5;28mself[39m[38;5;241m.[39m_bz_mode [38;5;241m=[39m mode
[0;32m--> 283[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/bz2.py:81[0m, in [0;36mBZ2File.__init__[0;34m(self, filename, mode, compresslevel)[0m
[1;32m     80[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(filename, ([38;5;28mstr[39m, [38;5;28mbytes[39m, os[38;5;241m.[39mPathLike)):
[0;32m---> 81[0m     [38;5;28mself[39m[38;5;241m.[39m_fp [38;5;241m=[39m [43m_builtin_open[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m     82[0m     [38;5;28mself[39m[38;5;241m.[39m_closefp [38;5;241m=[39m [38;5;28;01mTrue[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'pdb/protein_H.pdb'

The above exception was the direct cause of the following exception:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m protein [38;5;241m=[39m [43mmda[49m[38;5;241;43m.[39;49m[43mUniverse[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mpdb/protein_H.pdb[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:356[0m, in [0;36mUniverse.__init__[0;34m(self, topology, all_coordinates, format, topology_format, transformations, guess_bonds, vdwradii, fudge_factor, lower_bound, in_memory, in_memory_step, *coordinates, **kwargs)[0m
[1;32m    354[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(topology, Topology) [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m topology [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    355[0m     [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;241m=[39m _check_file_like(topology)
[0;32m--> 356[0m     topology [38;5;241m=[39m [43m_topology_from_file_like[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m,[49m
[1;32m    357[0m [43m                                        [49m[43mtopology_format[49m[38;5;241;43m=[39;49m[43mtopology_format[49m[43m,[49m
[1;32m    358[0m [43m                                        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    360[0m [38;5;28;01mif[39;00m topology [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    361[0m     [38;5;28mself[39m[38;5;241m.[39m_topology [38;5;241m=[39m topology

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:118[0m, in [0;36m_topology_from_file_like[0;34m(topology_file, topology_format, **kwargs)[0m
[1;32m    111[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    112[0m     [38;5;66;03m# There are 2 kinds of errors that might be raised here:[39;00m
[1;32m    113[0m     [38;5;66;03m# one because the file isn't present[39;00m
[1;32m    114[0m     [38;5;66;03m# or the permissions are bad, second when the parser fails[39;00m
[1;32m    115[0m     [38;5;28;01mif[39;00m (err[38;5;241m.[39merrno [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m
[1;32m    116[0m         errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]):
[1;32m    117[0m         [38;5;66;03m# Runs if the error is propagated due to no permission / file not found[39;00m
[0;32m--> 118[0m         [38;5;28;01mraise[39;00m sys[38;5;241m.[39mexc_info()[[38;5;241m1[39m] [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    119[0m     [38;5;28;01melse[39;00m:
[1;32m    120[0m         [38;5;66;03m# Runs when the parser fails[39;00m
[1;32m    121[0m         [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m([38;5;124m"[39m[38;5;124mFailed to load from the topology file [39m[38;5;132;01m{0}[39;00m[38;5;124m"[39m
[1;32m    122[0m                         [38;5;124m"[39m[38;5;124m with parser [39m[38;5;132;01m{1}[39;00m[38;5;124m.[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    123[0m                         [38;5;124m"[39m[38;5;124mError: [39m[38;5;132;01m{2}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(topology_file, parser, err))

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/core/universe.py:110[0m, in [0;36m_topology_from_file_like[0;34m(topology_file, topology_format, **kwargs)[0m
[1;32m    108[0m [38;5;28;01mtry[39;00m:
[1;32m    109[0m     [38;5;28;01mwith[39;00m parser(topology_file) [38;5;28;01mas[39;00m p:
[0;32m--> 110[0m         topology [38;5;241m=[39m [43mp[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    111[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    112[0m     [38;5;66;03m# There are 2 kinds of errors that might be raised here:[39;00m
[1;32m    113[0m     [38;5;66;03m# one because the file isn't present[39;00m
[1;32m    114[0m     [38;5;66;03m# or the permissions are bad, second when the parser fails[39;00m
[1;32m    115[0m     [38;5;28;01mif[39;00m (err[38;5;241m.[39merrno [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m
[1;32m    116[0m         errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]):
[1;32m    117[0m         [38;5;66;03m# Runs if the error is propagated due to no permission / file not found[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:210[0m, in [0;36mPDBParser.parse[0;34m(self, **kwargs)[0m
[1;32m    203[0m [38;5;28;01mdef[39;00m [38;5;21mparse[39m([38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    204[0m [38;5;250m    [39m[38;5;124;03m"""Parse atom information from PDB file[39;00m
[1;32m    205[0m 
[1;32m    206[0m [38;5;124;03m    Returns[39;00m
[1;32m    207[0m [38;5;124;03m    -------[39;00m
[1;32m    208[0m [38;5;124;03m    MDAnalysis Topology object[39;00m
[1;32m    209[0m [38;5;124;03m    """[39;00m
[0;32m--> 210[0m     top [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_parseatoms[49m[43m([49m[43m)[49m
[1;32m    212[0m     [38;5;28;01mtry[39;00m:
[1;32m    213[0m         bonds [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_parsebonds(top[38;5;241m.[39mids[38;5;241m.[39mvalues)

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:247[0m, in [0;36mPDBParser._parseatoms[0;34m(self)[0m
[1;32m    245[0m [38;5;28mself[39m[38;5;241m.[39m_wrapped_serials [38;5;241m=[39m [38;5;28;01mFalse[39;00m  [38;5;66;03m# did serials go over 100k?[39;00m
[1;32m    246[0m last_wrapped_serial [38;5;241m=[39m [38;5;241m100000[39m  [38;5;66;03m# if serials wrap, start from here[39;00m
[0;32m--> 247[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43mopenany[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m)[49m[43m [49m[38;5;28;43;01mas[39;49;00m[43m [49m[43mf[49m[43m:[49m
[1;32m    248[0m [43m    [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mline[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[43mf[49m[43m:[49m
[1;32m    249[0m [43m        [49m[43mline[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mline[49m[38;5;241;43m.[39;49m[43mstrip[49m[43m([49m[43m)[49m[43m  [49m[38;5;66;43;03m# Remove extra spaces[39;49;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/contextlib.py:137[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    135[0m [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39margs, [38;5;28mself[39m[38;5;241m.[39mkwds, [38;5;28mself[39m[38;5;241m.[39mfunc
[1;32m    136[0m [38;5;28;01mtry[39;00m:
[0;32m--> 137[0m     [38;5;28;01mreturn[39;00m [38;5;28mnext[39m([38;5;28mself[39m[38;5;241m.[39mgen)
[1;32m    138[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[1;32m    139[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mgenerator didn[39m[38;5;124m'[39m[38;5;124mt yield[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:318[0m, in [0;36mopenany[0;34m(datasource, mode, reset)[0m
[1;32m    274[0m [38;5;129m@contextmanager[39m
[1;32m    275[0m [38;5;28;01mdef[39;00m [38;5;21mopenany[39m(datasource, mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mrt[39m[38;5;124m'[39m, reset[38;5;241m=[39m[38;5;28;01mTrue[39;00m):
[1;32m    276[0m [38;5;250m    [39m[38;5;124;03m"""Context manager for :func:`anyopen`.[39;00m
[1;32m    277[0m 
[1;32m    278[0m [38;5;124;03m    Open the `datasource` and close it when the context of the :keyword:`with`[39;00m
[0;32m   (...)[0m
[1;32m    316[0m [38;5;124;03m    :func:`anyopen`[39;00m
[1;32m    317[0m [38;5;124;03m    """[39;00m
[0;32m--> 318[0m     stream [38;5;241m=[39m [43manyopen[49m[43m([49m[43mdatasource[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m,[49m[43m [49m[43mreset[49m[38;5;241;43m=[39;49m[43mreset[49m[43m)[49m
[1;32m    319[0m     [38;5;28;01mtry[39;00m:
[1;32m    320[0m         [38;5;28;01myield[39;00m stream

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:398[0m, in [0;36manyopen[0;34m(datasource, mode, reset)[0m
[1;32m    396[0m [38;5;28;01mfor[39;00m ext [38;5;129;01min[39;00m ([38;5;124m'[39m[38;5;124mbz2[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mgz[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m'[39m):  [38;5;66;03m# file == '' should be last[39;00m
[1;32m    397[0m     openfunc [38;5;241m=[39m read_handlers[ext]
[0;32m--> 398[0m     stream [38;5;241m=[39m [43m_get_stream[49m[43m([49m[43mdatasource[49m[43m,[49m[43m [49m[43mopenfunc[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[1;32m    399[0m     [38;5;28;01mif[39;00m stream [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    400[0m         [38;5;28;01mbreak[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:440[0m, in [0;36m_get_stream[0;34m(filename, openfunction, mode)[0m
[1;32m    435[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    436[0m     [38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this[39;00m
[1;32m    437[0m     [38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because[39;00m
[1;32m    438[0m     [38;5;66;03m# either the file isn't there or the permissions don't allow access.[39;00m
[1;32m    439[0m     [38;5;28;01mif[39;00m errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]:
[0;32m--> 440[0m         [38;5;28;01mraise[39;00m sys[38;5;241m.[39mexc_info()[[38;5;241m1[39m] [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    441[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[1;32m    442[0m [38;5;28;01mif[39;00m mode[38;5;241m.[39mstartswith([38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m):
[1;32m    443[0m     [38;5;66;03m# additional check for reading (eg can we uncompress) --- is this needed?[39;00m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/util.py:434[0m, in [0;36m_get_stream[0;34m(filename, openfunction, mode)[0m
[1;32m    432[0m [38;5;250m[39m[38;5;124;03m"""Return open stream if *filename* can be opened with *openfunction* or else ``None``."""[39;00m
[1;32m    433[0m [38;5;28;01mtry[39;00m:
[0;32m--> 434[0m     stream [38;5;241m=[39m [43mopenfunction[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[1;32m    435[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mIOError[39;00m, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m    436[0m     [38;5;66;03m# An exception might be raised due to two reasons, first the openfunction is unable to open the file, in this[39;00m
[1;32m    437[0m     [38;5;66;03m# case we have to ignore the error and return None. Second is when openfunction can't open the file because[39;00m
[1;32m    438[0m     [38;5;66;03m# either the file isn't there or the permissions don't allow access.[39;00m
[1;32m    439[0m     [38;5;28;01mif[39;00m errno[38;5;241m.[39merrorcode[err[38;5;241m.[39merrno] [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mENOENT[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEACCES[39m[38;5;124m'[39m]:

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:502[0m, in [0;36mbz2_pickle_open[0;34m(name, mode)[0m
[1;32m    499[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mOnly read mode ([39m[38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;124mrt[39m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m[38;5;124m) [39m[38;5;124m"[39m
[1;32m    500[0m                      [38;5;124m"[39m[38;5;124mfiles can be pickled.[39m[38;5;124m"[39m)
[1;32m    501[0m bz_mode [38;5;241m=[39m mode[38;5;241m.[39mreplace([38;5;124m"[39m[38;5;124mt[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m"[39m)
[0;32m--> 502[0m binary_file [38;5;241m=[39m [43mBZ2Picklable[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mbz_mode[49m[43m)[49m
[1;32m    503[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mt[39m[38;5;124m"[39m [38;5;129;01min[39;00m mode:
[1;32m    504[0m     [38;5;28;01mreturn[39;00m TextIOPicklable(binary_file)

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/site-packages/MDAnalysis/lib/picklable_file_io.py:283[0m, in [0;36mBZ2Picklable.__init__[0;34m(self, name, mode)[0m
[1;32m    281[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, name, mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m):
[1;32m    282[0m     [38;5;28mself[39m[38;5;241m.[39m_bz_mode [38;5;241m=[39m mode
[0;32m--> 283[0m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/biochemist-python/lib/python3.11/bz2.py:81[0m, in [0;36mBZ2File.__init__[0;34m(self, filename, mode, compresslevel)[0m
[1;32m     78[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mInvalid mode: [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m [38;5;241m%[39m (mode,))
[1;32m     80[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(filename, ([38;5;28mstr[39m, [38;5;28mbytes[39m, os[38;5;241m.[39mPathLike)):
[0;32m---> 81[0m     [38;5;28mself[39m[38;5;241m.[39m_fp [38;5;241m=[39m [43m_builtin_open[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m     82[0m     [38;5;28mself[39m[38;5;241m.[39m_closefp [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m     83[0m     [38;5;28mself[39m[38;5;241m.[39m_mode [38;5;241m=[39m mode_code

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'pdb/protein_H.pdb'

